com:
  ryq:
    UPLOADED_FOLDER: E://temp//
server:
  port: 8080
  tomcat:
    accesslog:
      encoding: UTF-8
spring:
  redis:
    database: 0
    host: 39.105.180.111
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://39.105.180.111:3306/inspiration?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:  #文件上传
      enabled: true
      max-file-size: 20MB   # 支持的最大文件
      max-request-size: 20MB #文件请求最大限制


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ryq.inspiration.pojo
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  file:
    path: login.log









